### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by pkramme** [HugoSmits86/nativewebp#3]
Hello, 

I am trying to write an resized image and I am getting this panic:
```
panic: runtime error: slice bounds out of range [::-316]

goroutine 1 [running]:
github.com/HugoSmits86/nativewebp.flatten({0x541828, 0xc00012c140})
        github.com/HugoSmits86/nativewebp@v0.9.0/writer.go:231 +0x1b2
github.com/HugoSmits86/nativewebp.WriteBitStreamData(0xc00011edb0, {0x541828, 0xc00012c140}, 0x4, {0x1, 0x0, 0x1, 0x0})
        github.com/HugoSmits86/nativewebp@v0.9.0/writer.go:98 +0x3d
github.com/HugoSmits86/nativewebp.Encode({0x540fe8, 0xc000128028}, {0x5416a8, 0xc00014e100})
        github.com/HugoSmits86/nativewebp@v0.9.0/writer.go:51 +0x27e
main.main()
        smartcrop/main.go:47 +0x4b7
```

**Comment by HugoSmits86** [comment]
I'm away from my laptop right now, but I have a good hunch about what might be causing the issue and will look into it tomorrow. In the meantime, could you let me know which package or code you used to resize the image? That way, I can test it directly when I get back. Thanks!

**Comment by pkramme** [comment]
Hey, your response slipped through. Thank you very much for the fix! The generating library was muesli/smartcrop

**Comment by HugoSmits86** [comment]
No worries! Hopefully, it's fixed now. I recreated it with an image that doesn’t have bounds min at zero which resulted in the same panic error.
